### ISSUE TITLE
Summary: Grade = Meets Expectations

### ISSUE THREAD

**Issue by jordanwillis** [aymengraoui/Capstone-VidBits#5]
Overall you did a fantastic job on this project!  It's no simple task to not only learn and apply TDD methodologies but also build the full stack app from the ground up!  Although a few tests were missing here and there and some code could be further optimized, it was very clear that you know exactly what you were doing!!

Hopefully you walked away from the course seeing the high value of TDD and will continue applying this approach on your future projects to come.

Keep up the great work!

**Comment by aymengraoui** [comment]
Thank you. I really appreciate you taking time for the review and of course ill apply TDD in next projects but I'm working with react and it was a little bit weird to work with Handlebars 😕 but ya its a good course. cheers 😄
